jobs:
  test:
    executor: node-executor
    environment:
      MONGOMS_SKIP_POSTINSTALL: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Generate coverage report
          command: npm run coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results
