version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            rm -rf node_modules
            npm install --ignore-scripts

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Jest Globally (if needed)
          command: npm install -g jest
      - run:
          name: Run Tests
          command: |
            cd blogs-backend
            npx jest --coverage --no-cache --verbose


workflows:
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
