version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd blogs-backend
            rm -rf node_modules
            npm install

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            cd blogs-backend
            chmod +x ./node_modules/.bin/jest
            npx jest --coverage --no-cache

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
