version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16.20.1
    working_directory: ~/repo

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Check Node.js Version
          command: node -v
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Generate coverage report
          command: npm run coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results

workflows:
  test_and_build:
    jobs:
      - test
