version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16  # Use the appropriate Node.js version for your project
    working_directory: ~/repo

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Generate coverage report
          command: npm run coverage  # Ensure you have a coverage script in your package.json
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
